name: camera_sqlite
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite: ^1.3.0
  path_provider: ^1.6.5
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.0
  image_picker: ^0.6.0+3
  camera: ^0.5.7+4
  path: ^1.6.4
  gallery_saver: ^1.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
